"""Missile display labels, independent of the pinned simulation model.

English short labels from the game localization snapshot retrieved 2026-09-30:
https://github.com/gszabi99/War-Thunder-Datamine/blob/master/lang.vromfs.bin_u/lang/units_weaponry.csv
Fallback IDs below have no matching localized short label in that snapshot;
their labels are formatted identifiers, without inferred missile nicknames.
"""

SOURCE_SHA256 = '9320535fc0bc76e289852a4f5790944174ec3f81593188bfac763d3ab78246c0'
FALLBACK_IDS = ('su_9m342', 'su_pl9', 'us_fim-92b', 'cn_pf10', 'us_aim_26b', 'us_aim_54b')

from functools import lru_cache
import json
from pathlib import Path


def display_name(key, rocket=None, *, labels=None):
    """Prefer the automatically synchronized game localization to the seed."""
    if labels is None:
        labels = synchronized_labels()
    for candidate in dict.fromkeys([key, (rocket or {}).get('bulletName', key)]):
        for name in ('weapons/' + candidate + '/short', candidate):
            if labels.get(name):
                return labels[name]
    return NAMES.get(key, key.replace('_', ' ').upper())


@lru_cache(maxsize=1)
def synchronized_labels():
    path = Path(__file__).resolve().parents[1] / 'references/missile-names.json'
    return json.loads(path.read_text(encoding='utf-8'))['labels'] if path.exists() else {}


NAMES = {'atam_mistral': 'Mistral',
 'atam_mistral_a129': 'Mistral',
 'br_maa_1': 'MAA-1',
 'br_maa_1_default': 'MAA-1',
 'cn_pf10': 'PF-10',
 'cn_pl11': 'PL-11',
 'cn_pl12': 'PL-12',
 'cn_pl12_default': 'PL-12',
 'cn_pl12a': 'PL-12A',
 'cn_pl12a_default': 'PL-12A',
 'cn_pl15': 'PL-15',
 'cn_pl15_default': 'PL-15',
 'cn_pl8b': 'PL-8B',
 'cn_pl8b_default': 'PL-8B',
 'cn_sd10a': 'SD-10',
 'cn_sd10a_default': 'SD-10',
 'cn_ty_90': 'TY-90',
 'fr_matra_super_530d': 'Matra Super 530D',
 'fr_matra_super_530d_default': 'Matra Super 530D',
 'fr_matra_super_530f': 'Matra Super 530F',
 'fr_matra_super_530f_default': 'Matra Super 530F',
 'fr_matra_super_530f_mirage_2000': 'Matra Super 530F',
 'fr_matra_super_530f_mirage_2000_default': 'Matra Super 530F',
 'fr_mica_em': 'MICA-EM',
 'fr_mica_em_default': 'MICA-EM',
 'fr_r_511_matra': 'Matra R511',
 'fr_r_530_matra_ir': 'Matra R530E',
 'fr_r_530_matra_radar': 'Matra R530',
 'fr_r_550_magic': 'Matra R550 Magic 1',
 'fr_r_550_magic_2': 'Matra R550 Magic 2',
 'fr_r_550_magic_2_default': 'Matra R550 Magic 2',
 'il_derby': 'Derby',
 'il_derby_default': 'Derby',
 'il_pyton_3': 'Python 3',
 'il_pyton_3_default': 'Python 3',
 'il_pyton_4': 'Python 4',
 'il_shafrir_1': 'Shafrir',
 'il_shafrir_2': 'Shafrir 2',
 'il_shafrir_2_default': 'Shafrir 2',
 'ir_fakour_90': 'Fakour-90',
 'ir_sedjil': 'Sedjeel',
 'it_aspide_1a': 'Aspide-1A',
 'jp_aam3': 'AAM-3',
 'jp_aam3_default': 'AAM-3',
 'jp_aam4': 'AAM-4',
 'jp_aam4_default': 'AAM-4',
 'r_darter': 'R-Darter',
 'r_darter_default': 'R-Darter',
 'ro_a91': 'A-91',
 'ro_a91_default': 'A-91',
 'su_9m336': '9M336',
 'su_9m342': '9M342',
 'su_9m39': '9M39',
 'su_pl2': 'PL-2',
 'su_pl2_default': 'PL-2',
 'su_pl5b': 'PL-5B',
 'su_pl5b_default': 'PL-5B',
 'su_pl5c': 'PL-5C',
 'su_pl5c_default': 'PL-5C',
 'su_pl5e2': 'PL-5EII',
 'su_pl5e2_default': 'PL-5EII',
 'su_pl7': 'PL-7',
 'su_pl8': 'PL-8',
 'su_pl8_default': 'PL-8',
 'su_pl9': 'PL-9',
 'su_r_13m': 'R-13M',
 'su_r_13m1': 'R-13M1',
 'su_r_13m1_default': 'R-13M1',
 'su_r_23r': 'R-23R',
 'su_r_23t': 'R-23T',
 'su_r_24r': 'R-24R',
 'su_r_24t': 'R-24T',
 'su_r_27er': 'R-27ER',
 'su_r_27er1': 'R-27ER1',
 'su_r_27er_default': 'R-27ER',
 'su_r_27et': 'R-27ET',
 'su_r_27et1': 'R-27ET1',
 'su_r_27r': 'R-27R',
 'su_r_27r1': 'R-27R1',
 'su_r_27r1_default': 'R-27R1',
 'su_r_27r_default': 'R-27R',
 'su_r_27t': 'R-27T',
 'su_r_27t1': 'R-27T1',
 'su_r_3r': 'R-3R',
 'su_r_3r_default': 'R-3R',
 'su_r_3s': 'R-3S',
 'su_r_3s_default': 'R-3S',
 'su_r_40rd': 'R-40RD',
 'su_r_40rd_default': 'R-40RD',
 'su_r_40td': 'R-40TD',
 'su_r_40td_default': 'R-40TD',
 'su_r_60': 'R-60',
 'su_r_60_default': 'R-60',
 'su_r_60m': 'R-60M',
 'su_r_60m_default': 'R-60M',
 'su_r_60mk': 'R-60MK',
 'su_r_60mk_default': 'R-60MK',
 'su_r_73': 'R-73',
 'su_r_73_default': 'R-73',
 'su_r_73e': 'R-73E',
 'su_r_73e_default': 'R-73E',
 'su_r_77': 'R-77',
 'su_r_77_1': 'R-77-1',
 'su_r_77_1_default': 'R-77-1',
 'su_r_77_default': 'R-77',
 'su_rvv_ae': 'RVV-AE',
 'su_rvv_ae_default': 'RVV-AE',
 'su_rvv_sd': 'RVV-SD',
 'su_rvv_sd_default': 'RVV-SD',
 'swd_rb24': 'RB24',
 'swd_rb24_default': 'RB24',
 'swd_rb24j': 'RB24J',
 'swd_rb24j_default': 'RB24J',
 'swd_rb27': 'RB27',
 'swd_rb28': 'RB28',
 'swd_rb71': 'RB71 (DF)',
 'swd_rb71_default': 'RB71 (DF)',
 'swd_rb74': 'RB 74',
 'swd_rb74_bol_pod': 'RB 74',
 'swd_rb74_default': 'RB 74',
 'swd_rb74m': 'RB 74(M)',
 'swd_rb74m_bol_pod': 'RB 74(M)',
 'swd_rb74m_default': 'RB 74(M)',
 'swd_rb99': 'RB 99',
 'swd_rb99_default': 'RB 99',
 'sws_flz_lwf_63': 'Flz Lwf 63',
 'sws_flz_lwf_63_75': 'Flz Lwf LL 63/75',
 'sws_flz_lwf_63_80': 'Flz Lwf 63/80',
 'sws_flz_lwf_ll_64': 'FL 64/79',
 'uk_firestreak': 'Firestreak',
 'uk_firestreak_default': 'Firestreak',
 'uk_firestreak_javelin': 'Firestreak',
 'uk_redtop': 'Red Top',
 'uk_skyflash_aim_7': 'Skyflash',
 'uk_skyflash_aim_7_dogfight': 'Skyflash (DF)',
 'uk_skyflash_aim_7_dogfight_default': 'Skyflash (DF)',
 'uk_skyflash_aim_7_dogfight_tornado': 'Skyflash (DF)',
 'uk_skyflash_aim_7_dogfight_tornado_default': 'Skyflash (DF)',
 'uk_skyflash_temp': 'Skyflash SuperTEMP',
 'uk_sraam': 'SRAAM',
 'uk_sraam_default': 'SRAAM',
 'us_aim4d_falcon': 'AIM-4G',
 'us_aim4f_falcon': 'AIM-4F',
 'us_aim4f_falcon_default': 'AIM-4F',
 'us_aim4g_falcon': 'AIM-4G',
 'us_aim4g_falcon_default': 'AIM-4G',
 'us_aim7c_sparrow': 'AIM-7C',
 'us_aim7d_sparrow': 'AIM-7D',
 'us_aim7e2_dogfight_sparrow': 'AIM-7E-2 (DF)',
 'us_aim7e_sparrow': 'AIM-7E',
 'us_aim7f_sparrow': 'AIM-7F',
 'us_aim7f_sparrow_default': 'AIM-7F',
 'us_aim7f_sparrow_f_14': 'AIM-7F',
 'us_aim7f_sparrow_fa_18': 'AIM-7F',
 'us_aim7m_sparrow': 'AIM-7M',
 'us_aim7m_sparrow_default': 'AIM-7M',
 'us_aim7m_sparrow_f_14': 'AIM-7M',
 'us_aim7m_sparrow_f_15': 'AIM-7M',
 'us_aim7m_sparrow_f_15_default': 'AIM-7M',
 'us_aim7m_sparrow_f_16': 'AIM-7M',
 'us_aim7m_sparrow_f_16_default': 'AIM-7M',
 'us_aim7m_sparrow_fa_18': 'AIM-7M',
 'us_aim7p_sparrow_fa_18': 'AIM-7P',
 'us_aim7p_sparrow_fa_18_default': 'AIM-7P',
 'us_aim92_stinger': 'ATAS',
 'us_aim92_stinger_atas_tiger': 'ATAS',
 'us_aim92_stinger_left': 'ATAS',
 'us_aim92_stinger_right': 'ATAS',
 'us_aim9b_fgw_2_sidewinder': 'AIM-9B FGW.2',
 'us_aim9b_sidewinder': 'AIM-9B',
 'us_aim9b_sidewinder_cwp': 'AIM-9B',
 'us_aim9b_sidewinder_default': 'AIM-9B',
 'us_aim9b_sidewinder_default_group': 'AIM-9B',
 'us_aim9c_sidewinder': 'AIM-9C',
 'us_aim9c_sidewinder_default': 'AIM-9C',
 'us_aim9c_sidewinder_default_group': 'AIM-9C',
 'us_aim9d_sidewinder': 'AIM-9D',
 'us_aim9d_sidewinder_cwp': 'AIM-9D',
 'us_aim9d_sidewinder_default': 'AIM-9D',
 'us_aim9d_sidewinder_default_group': 'AIM-9D',
 'us_aim9e_sidewinder': 'AIM-9E',
 'us_aim9e_sidewinder_default': 'AIM-9E',
 'us_aim9g_sidewinder': 'AIM-9G',
 'us_aim9g_sidewinder_default': 'AIM-9G',
 'us_aim9h_sidewinder': 'AIM-9H',
 'us_aim9j_sidewinder': 'AIM-9J',
 'us_aim9j_sidewinder_default': 'AIM-9J',
 'us_aim9l_i_1_sidewinder': 'AIM-9L/I-1',
 'us_aim9l_i_1_sidewinder_default': 'AIM-9L/I-1',
 'us_aim9l_i_sidewinder': 'AIM-9L/I',
 'us_aim9l_i_sidewinder_default': 'AIM-9L/I',
 'us_aim9l_sidewinder': 'AIM-9L',
 'us_aim9l_sidewinder_bol_pod': 'AIM-9L',
 'us_aim9l_sidewinder_default': 'AIM-9L',
 'us_aim9l_sidewinder_default_bol_pod': 'AIM-9L',
 'us_aim9m_sidewinder': 'AIM-9M',
 'us_aim9m_sidewinder_bol_pod': 'AIM-9M',
 'us_aim9m_sidewinder_default': 'AIM-9M',
 'us_aim9n_sidewinder': 'AIM-9N',
 'us_aim9p4_sidewinder': 'AIM-9P-4',
 'us_aim9p4_sidewinder_default': 'AIM-9P-4',
 'us_aim9p_sidewinder': 'AIM-9P',
 'us_aim9p_sidewinder_default': 'AIM-9P',
 'us_aim_120a': 'AIM-120A',
 'us_aim_120a_default': 'AIM-120A',
 'us_aim_120b': 'AIM-120B',
 'us_aim_120b_bol_pod': 'AIM-120B',
 'us_aim_120b_default': 'AIM-120B',
 'us_aim_120b_default_switzerland': 'Flz Lwl LL 97 AMRAAM',
 'us_aim_120b_switzerland': 'Flz Lwl LL 97 AMRAAM',
 'us_aim_120c_5': 'AIM-120C-5',
 'us_aim_120c_5_default': 'AIM-120C-5',
 'us_aim_120c_5_default_switzerland': 'Flz Lwl LL 97 AMRAAM 120C-5',
 'us_aim_120c_5_switzerland': 'Flz Lwl LL 97 AMRAAM 120C-5',
 'us_aim_120c_7': 'AIM-120C-7',
 'us_aim_120c_7_default': 'AIM-120C-7',
 'us_aim_120d': 'AIM-120D',
 'us_aim_120d_default': 'AIM-120D',
 'us_aim_26b': 'AIM-26B',
 'us_aim_54a': 'AIM-54A',
 'us_aim_54a_default': 'AIM-54A',
 'us_aim_54b': 'AIM-54B',
 'us_aim_54c': 'AIM-54C',
 'us_aim_54c_default': 'AIM-54C',
 'us_aim_54c_plus': 'AIM-54C+',
 'us_aim_54c_plus_default': 'AIM-54C+',
 'us_fim-92b': 'FIM-92B'}
